### ISSUE TITLE
Exception "Protocol message end-group tag did not match expected tag" when setting args.format = json

### ISSUE THREAD

**Issue by asalhani** [camunda-community-hub/zeebe-redis-exporter#204]
As per README.md, 
` exporters:
      redis:
        className: io.zeebe.redis.exporter.RedisExporter
        jarPath: exporters/zeebe-redis-exporter-1.0.0-jar-with-dependencies.jar
        args:
          cleanupCycleInSeconds: -1
          maxTimeToLiveInSeconds: -1
          format: "json"`

Format property can take either of 2 values [protobuf|json]
When setting to `protobuf` the listner is working fine.

However, when setting it to "json", the following excption is being thrown when listner activating:

> 2024-08-17T18:53:22.173+03:00 ERROR 22244 --- [tasklistapp] [pool-5-thread-1] io.zeebe.redis.connect.java.ZeebeRedis   : Consumer[group=USER_TASK_CONSUMER_GROUP, id=consumer-1] failed to read from streams 'zeebe:*'
com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
	at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:114) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:615) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:811) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:494) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(GeneratedMessageV3.java:864) ~[protobuf-java-3.25.1.jar:na]
	at io.zeebe.exporter.proto.Schema$Record$Builder.mergeFrom(Schema.java:995) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
	at io.zeebe.exporter.proto.Schema$Record$1.parsePartialFrom(Schema.java:1166) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
	at io.zeebe.exporter.proto.Schema$Record$1.parsePartialFrom(Schema.java:1158) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
	at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:135) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185) ~[protobuf-java-3.25.1.jar:na]
	at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:25) ~[protobuf-java-3.25.1.jar:na]
	at io.zeebe.exporter.proto.Schema$Record.parseFrom(Schema.java:754) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
	at io.zeebe.redis.connect.java.ZeebeRedis.handleRecord(ZeebeRedis.java:341) ~[zeebe-redis-connector-1.0.0.jar:1.0.0]
	at io.zeebe.redis.connect.java.ZeebeRedis.readNext(ZeebeRedis.java:300) ~[zeebe-redis-connector-1.0.0.jar:1.0.0]
	at io.zeebe.redis.connect.java.ZeebeRedis.readFromStream(ZeebeRedis.java:270) ~[zeebe-redis-connector-1.0.0.jar:1.0.0]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]

I need to set it to JSON because "protobuf" does not render the value correctly when checking record in Redis Insight

Format= json ==> value can be inspected in Redis Insight
<img width="367" alt="image" src="https://github.com/user-attachments/assets/96c887d7-efcc-4194-9159-03711714ae44">

Format= protobuf ==> value can't retrived in Redis insight
<img width="494" alt="image" src="https://github.com/user-attachments/assets/c88ce28e-0ef4-4971-856e-257b6342e0b5">

**Comment by asalhani** [comment]
> As per README.md, ` exporters: redis: className: io.zeebe.redis.exporter.RedisExporter jarPath: exporters/zeebe-redis-exporter-1.0.0-jar-with-dependencies.jar args: cleanupCycleInSeconds: -1 maxTimeToLiveInSeconds: -1 format: "json"`
> 
> Format property can take either of 2 values [protobuf|json] When setting to `protobuf` the listner is working fine.
> 
> However, when setting it to "json", the following excption is being thrown when listner activating:
> 
> > 2024-08-17T18:53:22.173+03:00 ERROR 22244 --- [tasklistapp] [pool-5-thread-1] io.zeebe.redis.connect.java.ZeebeRedis   : Consumer[group=USER_TASK_CONSUMER_GROUP, id=consumer-1] failed to read from streams 'zeebe:*'
> > com.google.protobuf.InvalidProtocolBufferException: Protocol message end-group tag did not match expected tag.
> > at com.google.protobuf.InvalidProtocolBufferException.invalidEndTag(InvalidProtocolBufferException.java:114) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.CodedInputStream$ArrayDecoder.checkLastTagWas(CodedInputStream.java:615) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.CodedInputStream$ArrayDecoder.readGroup(CodedInputStream.java:811) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.UnknownFieldSet$Builder.mergeFieldFrom(UnknownFieldSet.java:494) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.GeneratedMessageV3$Builder.parseUnknownField(GeneratedMessageV3.java:864) ~[protobuf-java-3.25.1.jar:na]
> > at io.zeebe.exporter.proto.Schema$Record$Builder.mergeFrom(Schema.java:995) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
> > at io.zeebe.exporter.proto.Schema$Record$1.parsePartialFrom(Schema.java:1166) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
> > at io.zeebe.exporter.proto.Schema$Record$1.parsePartialFrom(Schema.java:1158) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
> > at com.google.protobuf.AbstractParser.parsePartialFrom(AbstractParser.java:135) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:168) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:180) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:185) ~[protobuf-java-3.25.1.jar:na]
> > at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:25) ~[protobuf-java-3.25.1.jar:na]
> > at io.zeebe.exporter.proto.Schema$Record.parseFrom(Schema.java:754) ~[zeebe-exporter-protobuf-1.6.1.jar:1.6.1]
> > at io.zeebe.redis.connect.java.ZeebeRedis.handleRecord(ZeebeRedis.java:341) ~[zeebe-redis-connector-1.0.0.jar:1.0.0]
> > at io.zeebe.redis.connect.java.ZeebeRedis.readNext(ZeebeRedis.java:300) ~[zeebe-redis-connector-1.0.0.jar:1.0.0]
> > at io.zeebe.redis.connect.java.ZeebeRedis.readFromStream(ZeebeRedis.java:270) ~[zeebe-redis-connector-1.0.0.jar:1.0.0]
> > at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
> > at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264) ~[na:na]
> > at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
> > at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
> > at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
> > at java.base/java.lang.Thread.run(Thread.java:842) ~[na:na]
> 
> I need to set it to JSON because "protobuf" does not render the value correctly when checking record in Redis Insight
> 
> Format= json ==> value can be inspected in Redis Insight <img alt="image" width="367" src="https://private-user-images.githubusercontent.com/5410830/358855843-96c887d7-efcc-4194-9159-03711714ae44.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTEwMjQsIm5iZiI6MTcyMzkxMDcyNCwicGF0aCI6Ii81NDEwODMwLzM1ODg1NTg0My05NmM4ODdkNy1lZmNjLTQxOTQtOTE1OS0wMzcxMTcxNGFlNDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTYwNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjlkNzEzNTg4MTMyNmExMGM3ZDg1ZjZhNDE4ZGQzZjdmYzQyNjFhZDE3MzdlNDgzNjdhZTFlOGYyZWRiMGYxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.gQOvVl3dKs79NXyY6jIvIxtdghgWU75OJGaB39-bHW8">
> 
> Format= protobuf ==> value can't retrived in Redis insight <img alt="image" width="494" src="https://private-user-images.githubusercontent.com/5410830/358856087-c88ce28e-0ef4-4971-856e-257b6342e0b5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM5MTEwMjQsIm5iZiI6MTcyMzkxMDcyNCwicGF0aCI6Ii81NDEwODMwLzM1ODg1NjA4Ny1jODhjZTI4ZS0wZWY0LTQ5NzEtODU2ZS0yNTdiNjM0MmUwYjUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MTdUMTYwNTI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMyZWI0ZWYyMjg4NGJiOWQwN2RkMWNmNzNhYTRlYzU1NjIyYTlkMzhjMjMyNmJiODlkOGYzYmQ1NDM3NDhkNCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.5Gl_kgOxjdqCn5mKz6hk1N0L69oUTIjQQL_MHWbJlNk">

@VonDerBeck

**Comment by VonDerBeck** [comment]
Hi @asalhani,

even if the exporter itself is able to (optionally) export events as JSON, the connector is designed to use the default which is protobuf. So this is not an error.

**Comment by asalhani** [comment]
@VonDerBeck 
Is there is a way to configure both exporter and connector to transmit data as JSON instead of protobuf?
